### ISSUE TITLE
Picom crashes with almost every window close/workspace change

### ISSUE THREAD

**Issue by frebib** [tryone144/compton#41]
Build is tryone144/compton@feature/dual_kawase rebased against https://github.com/yshui/picom/commit/b652e8b58d942730f8c772f384c2d1004660b301

Crashes look to be caused by the assertion added in https://github.com/yshui/picom/commit/a23bac727cb7e5843a0499bc7451d8d1997ff2c8

```
Apr 05 21:45:26 frebib-PC.nerdhouse.io picom[35589]: picom: ../src/backend/backend.c:221: paint_all_new: Assertion `blur_opacity >= 0 && blur_opacity <= 1' failed.
Apr 05 21:45:26 frebib-PC.nerdhouse.io systemd[4272]: picom.service: Main process exited, code=dumped, status=6/ABRT
Apr 05 21:45:26 frebib-PC.nerdhouse.io systemd[4272]: picom.service: Failed with result 'core-dump'.
Apr 05 21:45:26 frebib-PC.nerdhouse.io systemd-coredump[35720]: Process 35589 (picom) of user 1000 dumped core.

                                                                Stack trace of thread 35589:
                                                                #0  0x00007f3427d4ace5 raise (libc.so.6 + 0x3bce5)
                                                                #1  0x00007f3427d34857 abort (libc.so.6 + 0x25857)
                                                                #2  0x00007f3427d34727 __assert_fail_base.cold (libc.so.6 + 0x25727)
                                                                #3  0x00007f3427d43426 __assert_fail (libc.so.6 + 0x34426)
                                                                #4  0x0000561193d4eb99 paint_all_new (picom + 0x35b99)
                                                                #5  0x0000561193d27d09 _draw_callback (picom + 0xed09)
                                                                #6  0x0000561193d28ab9 draw_callback (picom + 0xfab9)
                                                                #7  0x00007f34286bf033 ev_invoke_pending (libev.so.4 + 0x5033)
                                                                #8  0x00007f34286c2902 ev_run (libev.so.4 + 0x8902)
                                                                #9  0x0000561193d247f3 session_run (picom + 0xb7f3)
                                                                #10 0x00007f3427d36023 __libc_start_main (libc.so.6 + 0x27023)
                                                                #11 0x0000561193d25bfe _start (picom + 0xcbfe)
```

Config: https://gist.github.com/frebib/76790ba48c0a2f51b352f0be0c2b4fa1/raw

**Comment by tryone144** [comment]
Using `inactive-opacity` in combination with fading did result in alpha-clipping of the blur-texture in the new backends. This will be fixed with https://github.com/yshui/picom/pull/364.

There is another edge-case currently which won't be handled by the above PR. But there does not seem to be a consensus for a suitable solution found yet (see discussion https://github.com/yshui/picom/pull/318#discussion_r383043984).

**Comment by frebib** [comment]
Whilst trying to see if that change fixes it, there is a conflict between https://github.com/tryone144/picom/commit/e2813547b9b6c9eb0cec81f2c8beb9f14fab3610 and https://github.com/yshui/picom/pull/364/commits/285dee3605ecfd3b26676cd7c5b534d67a1dcc1a#diff-502aafee6e0b1afed37739f367a9a598
I wasn't sure which to keep, but adding both seems to not help (I think it's crashing more frequently now?)
I'll try dropping the older commit and rebuild.
I don't have much/any context on how this works, I'm just treating the code as a black box because it goes way over my head :D

(edit: even dropping out e2813547b9b6c9eb0cec81f2c8beb9f14fab3610 doesn't help, but it's back to the slightly lower frequency than with it)

I've pushed the tree that I'm building to here, if it helps
https://github.com/frebib/picom/tree/dual_kawase

**Comment by tryone144** [comment]
Drop https://github.com/tryone144/picom/commit/e2813547b9b6c9eb0cec81f2c8beb9f14fab3610 and take the ones from https://github.com/yshui/picom/pull/364. The former will become invalid once the PR is merged.

These commits will not help with the underlying issue of `blur_opacity` becoming larger than 1 sometimes. This might actually be due to sudden changes in `w->opacity_target` while fading the window. If you want a quick and dirty workaround just add
```c
blur_opacity = clamp(blur_opacity, 0, 1);
```
before the offending `assert()` [here](https://github.com/frebib/picom/blob/20be80bc6baa4622f3077e92d19333c603569fd6/src/backend/backend.c#L236). This will make sure `blur_opacity` is between 0 and 1.

The grown codebase of compton/picom definitely seems to work like magic sometimes. yshui did a great job at making it more maintainable already. :smile:

**Comment by frebib** [comment]
I'll have to think about how to manage this long-term. Hopefully the PR is pulled in soon and I won't have to do too much hacking. I'm already up to two rebases in the PKGBUILD and there are conflicts. I'm resisting the urge to fork, merge and build against that, but it may be required. I'll sleep on it and try in the morning. Thanks for the help :)

(edit: did what you suggested above and seems to be holding for now, ta)

**Comment by tryone144** [comment]
If you want to test this:
I've pushed new commits to https://github.com/tryone144/picom/tree/fix/blur-background-fixed which replace the previous ones. These should fix the problem without any hacks needed.

**Comment by tryone144** [comment]
https://github.com/yshui/picom/pull/364 has been merged upstream.
