### ISSUE TITLE
No blur on experimental branch

### ISSUE THREAD

**Issue by erdemoney** [tryone144/compton#46]
Platform: Void Linux glibc

GPU, drivers, and screen setup: laptop screen , intel integrated graphics

Compton version: feature/dual_kawase branch, picom (vgit-c67d7)

Compton configuration: simple config for testing

inactive-opacity = 0.6;
active-opacity = 0.8;

blur-method = "dual_kawase";
blur-strength = 6.9;

backend = "glx";
### Steps of reproduction
Install experimental branch from source. Run via "picom --experimental-backends" with above configuration.

### Expected behavior
Pretty blurred windows

### Current Behavior & Other details
Windows are only transparent with no blur. I have tried configuring it only with command line flags (i.e picom --experimental-backends --blur-method dual_kawase --backend glx), and  dropping in other peoples configs for this branch and still have no blur only transparency.

**Comment by erdemoney** [comment]
I just added "blur-background-fixed = true" to my config and have blur! Not sure if this is expected behavior but its working now.

**Comment by tryone144** [comment]
Just for future reference: `blur-background-fixed = true` fixes your issue here because this implementation adjusts "blur-opacity" based on the window opacity (see related #33, #25). This has already been changed in the upstream PR, to avoid this kind of confusion.

Furthermore, the dual-filter kawase algorithm only supports integer strength-levels. Your setting of `blur-strength = 6.9;` will be interpreted as level 6.
