### ISSUE TITLE
Kawase blur distorted

### ISSUE THREAD

**Issue by kirillsurkov** [tryone144/compton#49]
Platform: Ubuntu Desktop 20.04 amd64

GPU, drivers, and screen setup: NVidia GTX 850M, nvidia-drivers 440.100, one monitor

Compton version: 241bbc5 from this repository

Compton configuration: 
```
backend = "glx";

blur-background = true;
blur-background-frame = true;
blur-kern = "5x5gaussian";
blur-method = "kawase";
blur-strength = 12;
resize-damage = 12;

```
### Steps of reproduction

I set transparency of my gnome terminal around 25%

### Expected behavior

I expected to see smooth blur

### Current Behavior & Other details

Blur is distorted
![2020-07-12-143434_1920x1080_scrot](https://user-images.githubusercontent.com/37578206/87245612-4ce8b100-c44f-11ea-81b9-bad921c72f71.png)

How can I fix it? Seems like my monitor depth is losing some bits, but I don't know exactly what it is. I just want smooth blur.
Thank you!

**Comment by tryone144** [comment]
This sounds like [color banding](https://en.wikipedia.org/wiki/Colour_banding) to me. Your screenshot looks fine on my screen with no noticeable artifacts.

Does the above screenshot share the same artifacts with what you see when running compton? Are they still visible if you run compton with the default box-blur, the xrender backend or no compositor at all? Do other compositors produce the same artifacts (in particular interested in [picom](https://github.com/yshui/picom)?

Could be a problem with the OpenGL driver or the Xserver configuration.

**Comment by kirillsurkov** [comment]
This is how screenshot looks on my IPhone screen:
![IMG_3862](https://user-images.githubusercontent.com/37578206/87293858-94347780-c50b-11ea-9929-ea9827e12cf1.PNG)
So, banding is visible regardless of screen.

This is how it looks with box3x3 kernel:
![image](https://user-images.githubusercontent.com/37578206/87294373-5ab03c00-c50c-11ea-8353-bd426909b4ca.png)

This is how it looks with your picom feature/dual_kawase branch using this config:
```
backend = "glx";

blur-background = true;
blur-background-frame = true;
blur-kern = "3x3box";
blur-method = "dual_kawase";
blur-strength = 6;
resize-damage = 6;
```
![image](https://user-images.githubusercontent.com/37578206/87294318-3e140400-c50c-11ea-9c2a-72f10950cdcf.png)


My Xserver has no configuration at all(no xorg.conf file), so it using the default configuration. It's 24bit depth by default, which should be enough.
Could it be algorithm problem?

**Comment by tryone144** [comment]
These screenshots look fine. The iPhone one shows a bit of banding mostly due to the zoom of the original image.

If you open these screenshots in e.g. GIMP and take a look at the actual pixel values you can see that they are literally 1 bit away from each other. So each band in the screenshots it actually just a single step.

There isn't much you can do about that unless you change to a screen with more than 8 bits per color-channel. Picom should be able to handle that, but I couldn't find explicit confirmation that it works.
That said, these artifacts might be amplified by the actual screen calibration and some color-calibration profiles.

For comparison, [this wallpaper](https://raw.githubusercontent.com/tryone144/dotfiles/wallpaper/Archigon/archigon_2560x1440.png) should show the same banding-effects due to its slight greyscale gradient.

**Comment by kirillsurkov** [comment]
Yes, it's really just 1 bit from each other. Very interesting. In computer games I see smooth gradients everywhere - are they using dithering or more bits per channel?

What about your wallpaper - I was able to do more smoother gradient with GIMP.
![image](https://user-images.githubusercontent.com/37578206/87304402-6f490000-c51d-11ea-87b0-a45788937e0a.png)

Seems like it's achieved by dithering. Is it hard to implement it in compton? Because increasing bits per channel I think may result more problems than it solve.

**Comment by tryone144** [comment]
> Yes, it's really just 1 bit from each other. Very interesting. In computer games I see smooth gradients everywhere - are they using dithering or more bits per channel?

Scenes in games usually have much steeper gradients with more colors which is way less of a problem. Adding some noise (either by dithering or just a simple noise texture) usually breaks the color-banding patterns.

> What about your wallpaper - I was able to do more smoother gradient with GIMP.
>
> I think that it's achieved by dithering. Is it hard to implement it in compton? Because increasing bits per channel I think may result more problems than it solve.

The wallpaper was created with inkscape and has a rather shallow true grayscale gradient. GIMP's gradient isn't truly grayscale anymore, but increases/decreases each channel one-by-one creating three steps instead of one, which is some kind of dithering, true.
Adding dithering as a post-processing step should certainly be possible, but I am not so sure on what scale it should be applied.
Dithering the windows may actually already be possible with a custom window shader (see `--glx-fshader-win` option).

**Comment by kirillsurkov** [comment]
Thank you! I'll see what I can do to make it look better and maybe make some commits if I achieve some result. Closing issue.
