### ISSUE TITLE
Build docs failed on Linux Mint 18.3

### ISSUE THREAD

**Issue by aasril** [tryone144/compton#8]
Platform: Linux Mint 18.3 (Based on Ubuntu 16.04).

GPU, drivers, and screen setup: A Lenovo G400 laptop with Intel GPU.

Compton version: Both latest release version and the dual_kawase branch from git.

### Steps of reproduction

    $ make 

finished with a bunch of [warnings](https://github.com/tryone144/compton/files/3047124/compton_make.txt)

    $ make docs

failed with this Error

```
a2x --format manpage man/compton.1.asciidoc
  File "/usr/bin/a2x", line 76
    print '%s: %s' % (PROG,msg)
                 ^
SyntaxError: invalid syntax
Makefile:146: recipe for target 'man/compton.1' failed
make: *** [man/compton.1] Error 1
```

gcc is v6.5.0

**Comment by tryone144** [comment]
Hi,

Those warnings aren't critical and should all be fixed in yshui's maintained fork.

Regarding the failed `make docs`: It looks like an error in your distributions `/usr/bin/a2x` executable of the asciidoc package. On my system it's a python2 script and I'm guessing there is a problem with the python3 interpreter being invoked while the script uses python2 syntax.

You may look at the first line of that file to find out which interpreter is invoked and then run it manually with the `--version` flag.

**Comment by aasril** [comment]
That's exactly the problem! 

I had `update-alternatives` link `python`  to python3 instead of python2. Changing it back to python2 solves the error.

Now I have:
    $ compton --version
    git-v0.1_beta2-95-g241bbc5-2018-02-22

That should be correct, right?

Edit: Yes, that's correct.
I'm closing this issue. Thanks @tryone144
